// <auto-generated />
using System;
using LingoAITutor.Host.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LingoAITutor.Host.Migrations
{
    [DbContext(typeof(LingoDbContext))]
    [Migration("20230926184833_progressDetails")]
    partial class progressDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LingoAITutor.Host.Entities.RangeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Progress")
                        .HasColumnType("float");

                    b.Property<int>("StartPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("UserProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WordsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProgressId");

                    b.ToTable("RangeProgresses");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstimationNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseNumber")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.UserWordProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CorrectUses")
                        .HasColumnType("int");

                    b.Property<int?>("EstimationExerciseNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("EstimationExerciseResult")
                        .HasColumnType("bit");

                    b.Property<bool>("FailedToUseFlag")
                        .HasColumnType("bit");

                    b.Property<int>("NonUses")
                        .HasColumnType("int");

                    b.Property<int>("ReplacedBySynonyms")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WordID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("WorkOutStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.HasIndex("WordID");

                    b.ToTable("UserWordProgresses");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FrequencyRank")
                        .HasColumnType("real");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XOnMap")
                        .HasColumnType("int");

                    b.Property<int>("YOnMap")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.RangeProgress", b =>
                {
                    b.HasOne("LingoAITutor.Host.Entities.UserProgress", "UserProgress")
                        .WithMany("RangeProgresses")
                        .HasForeignKey("UserProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.UserWordProgress", b =>
                {
                    b.HasOne("LingoAITutor.Host.Entities.User", "User")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LingoAITutor.Host.Entities.Word", "Word")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.User", b =>
                {
                    b.Navigation("UserWordProgresses");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.UserProgress", b =>
                {
                    b.Navigation("RangeProgresses");
                });

            modelBuilder.Entity("LingoAITutor.Host.Entities.Word", b =>
                {
                    b.Navigation("UserWordProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
